<?php
/**
 * Language labels for database tables/fields belonging to extension "sk_calendar"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"tx_skcalendar_category" => "Category",	
		"tx_skcalendar_category.title" => "Title",	
		"tx_skcalendar_category.icon" => "Icon",	
		"tx_skcalendar_category.color" => "Color",	
		"tx_skcalendar_organizer" => "Organizer",	
		"tx_skcalendar_organizer.name" => "Name",	
		"tx_skcalendar_organizer.link" => "Link",	
		"tx_skcalendar_organizer.logo" => "Logo",	
		"tx_skcalendar_organizer.phone" => "Phone",	
		"tx_skcalendar_organizer.email" => "Email",	
		"tx_skcalendar_location" => "Location",	
		"tx_skcalendar_location.title" => "Title",	
		"tx_skcalendar_location.link" => "Link",	
		"tx_skcalendar_location.street" => "Street",	
		"tx_skcalendar_location.zip" => "ZIP",	
		"tx_skcalendar_location.city" => "City",	
		"tx_skcalendar_targetgroup" => "Target audience",	
		"tx_skcalendar_targetgroup.title" => "Title",	
		"tx_skcalendar_targetgroup.icon" => "Icon",	
		"tx_skcalendar_events" => "Events",	
		"tx_skcalendar_events.title" => "Title",	
		"tx_skcalendar_events.date" => "Date",	
		"tx_skcalendar_events.duration" => "Time (from - to)",	
		"tx_skcalendar_events.start_time" => "Begin",	
		"tx_skcalendar_events.end_time" => "End time",	
		"tx_skcalendar_events.wholeday" => "Wholeday event",	
		"tx_skcalendar_events.link" => "Link",	
		"tx_skcalendar_events.cost" => "Cost",	
		"tx_skcalendar_events.description" => "Description",	
		"tx_skcalendar_events.image" => "Image",	
		"tx_skcalendar_events.highlight" => "Highlight event",	
		"tx_skcalendar_events.fe_owner" => "Front-End user",	
		"tx_skcalendar_events.pages" => "Related pages",	
		"tx_skcalendar_events.exeptions" => "Exeptions for recurring events",	
		"tx_skcalendar_events.recurring.I.0" => "none",	
		"tx_skcalendar_events.recurring.I.1" => "daily",	
		"tx_skcalendar_events.recurring.I.2" => "weekly",	
		"tx_skcalendar_events.recurring.I.3" => "monthly",	
		"tx_skcalendar_events.recurring.I.4" => "yearly",	
		"tx_skcalendar_events.recurring.I.5" => "monthly (certain weekday)",	
		"tx_skcalendar_events.recurring" => "Recurring event",	
		"tx_skcalendar_events.recurr_until" => "Recurring event until",	
		"tx_skcalendar_events.category" => "Category",	
		"tx_skcalendar_events.organizer" => "Organizer",	
		"tx_skcalendar_events.targetgroup" => "Target audience",	
		"tx_skcalendar_events.location" => "Location",
		"tx_skcalendar_exeptions" => "Exeption for recurring event",
		"tx_skcalendar_exeptions.event" => "Recurring event",
		"tx_skcalendar_exeptions.exeptdate" => "Exept on Date",
		"tx_skcalendar_exeptions.substitute_event" => "Substitute event",
		"tt_content.list_type" => "VCE Calendar",	
	),
	"de" => Array (
		"tx_skcalendar_category" => "Kategorie",	
		"tx_skcalendar_category.title" => "Titel",	
		"tx_skcalendar_category.icon" => "Icon",	
		"tx_skcalendar_category.color" => "Farbe",	
		"tx_skcalendar_organizer" => "Veranstalter",	
		"tx_skcalendar_organizer.name" => "Name",	
		"tx_skcalendar_organizer.link" => "Link",	
		"tx_skcalendar_organizer.logo" => "Logo",	
		"tx_skcalendar_organizer.phone" => "Telefon",	
		"tx_skcalendar_organizer.email" => "E-Mail",	
		"tx_skcalendar_location" => "Veranstaltungsort",	
		"tx_skcalendar_location.title" => "Titel",	
		"tx_skcalendar_location.link" => "Link",	
		"tx_skcalendar_location.street" => "Straße",	
		"tx_skcalendar_location.zip" => "PLZ",	
		"tx_skcalendar_location.city" => "Stadt",	
		"tx_skcalendar_targetgroup" => "Zielgruppe",	
		"tx_skcalendar_targetgroup.title" => "Titel",	
		"tx_skcalendar_targetgroup.icon" => "Icon",	
		"tx_skcalendar_events" => "Termin",	
		"tx_skcalendar_events.title" => "Titel",	
		"tx_skcalendar_events.date" => "Datum",	
		"tx_skcalendar_events.duration" => "Zeitraum",	
		"tx_skcalendar_events.start_time" => "Anfang",	
		"tx_skcalendar_events.end_time" => "Ende",	
		"tx_skcalendar_events.wholeday" => "Ganztagesereignis",	
		"tx_skcalendar_events.link" => "Link",	
		"tx_skcalendar_events.cost" => "Kosten",	
		"tx_skcalendar_events.description" => "Beschreibung",	
		"tx_skcalendar_events.image" => "Bild",	
		"tx_skcalendar_events.highlight" => "Termin markieren",	
		"tx_skcalendar_events.fe_owner" => "Front-End User",	
		"tx_skcalendar_events.pages" => "Verknüpfte Seiten",	
		"tx_skcalendar_events.exeptions" => "Ausnahmen bei Wiederholungsterminen",	
		"tx_skcalendar_events.recurring.I.0" => "keine",	
		"tx_skcalendar_events.recurring.I.1" => "täglich",	
		"tx_skcalendar_events.recurring.I.2" => "wöchentlich",	
		"tx_skcalendar_events.recurring.I.3" => "monatlich",	
		"tx_skcalendar_events.recurring.I.4" => "jährlich",	
		"tx_skcalendar_events.recurring.I.5" => "monatlich (bestimmter Wochentag)",	
		"tx_skcalendar_events.recurring" => "Terminwiederholung",	
		"tx_skcalendar_events.recurr_until" => "Wiederholung bis",	
		"tx_skcalendar_events.category" => "Kategorie",	
		"tx_skcalendar_events.organizer" => "Veranstalter",	
		"tx_skcalendar_events.targetgroup" => "Zielgruppe",	
		"tx_skcalendar_events.location" => "Veranstaltungsort",
		"tx_skcalendar_exeptions" => "Ausnahme Wiederholungstermin",
		"tx_skcalendar_exeptions.event" => "Wiederholungstermin",
		"tx_skcalendar_exeptions.exeptdate" => "Ausnahmedatum",
		"tx_skcalendar_exeptions.substitute_event" => "Ersatztermin",
		"tt_content.list_type" => "VCE Kalender",
	),
);
?>