<?php
/**
 * Language labels for plugin "tx_skcalendar_pi1"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"choose_month" => "Choose month",
		"time" => "Time",
		"show" => "Display",
		"of" => "of",
		"all_month" => "Show all months",
		"other_views" => "Other views",
		"month_view" => "monthly view",
		"week_view" => "Weekly view",
		"year_view" => "Wholeyearview as PDF",
		"next_month" => "next month",
		"prev_month" => "previous month",
		"next_week" => "next week",
		"prev_week" => "previous week",
		"filter_view" => "filter view",
		"all_cat" => "all categories",
		"all_location" => "all locations",
		"all_organizer" => "all organizers",
		"all_targetgroup" => "all targetgroups",
		"filter_error" => "Filtering is not possible. You need at least two categories, two targetgroups, two organizers or two locations. You can also disable this warning.",
		"more" => "more",
		"here" => "here",
		"cost" => "Cost",
		"date" => "Date",
		"back" => "back",
		"further_information" => "Further information",
		"category" => "Category",
		"organizer" => "Organizer",
		"targetgroup" => "Targetgroup",
		"dteinheit" => "German reunion",
		"mai" => "First of may",
		"newyear" => "Newyear",
		"threekings" => "Dreikönig",
		"christmas25" => "Christmas",
		"advent1" => "1. Advent",
		"advent2" => "2. Advent",
		"advent3" => "3. Advent",
		"advent4" => "4. Advent",
		"easter" => "Easter",
		"easterfr" => "Karfreitag",
		"pentacost" => "Pentacost",
		"pentacostmo" => "Pentacost Monday",
		"mariaehf" => "Mariahimmelfahrt",
		"allerheilig" => "All hallows",
		"christmas26" => "2. Weihnachtsf.",
		"christihf" => "Christ. Himmelf.",
		"fronleich" => "Fronleichnam",
		"pdf_generated" => "The calendar has been generated and download should start automatically",
		"dl_pdf" => "If the download doesn't start please click ",
		"the" => "the",
		"description"=>"Description",
		"begin" => "start",
		"clock" => "Clock",
		"until" => "until",
		"no_entries" => "No Events could be found.",
		"do_filter" => "Filter view",
		"searchword" => "Searchword",
		"choose_cat" => "Choose category",
		"choose_loc" => "Choose location",
		"choose_org" => "Choose organizer",
		"choose_tar" => "Choose targetgroup",
		"archive_make_selection" => "Please specify your search",
		"page" => "Page",
		
		// for registration module How could this be done more elegant?
		"tx_skcalregistration_register_date" => "Register until",
		"tx_skcalregistration_register_tolate" => "Registration not possible any more",
		"tx_skcalregistration_register_files" => "Files",		
		"tx_skcalregistration_register_remarks" => "Registration",		
		),
	"dk" => Array (
	),
	"de" => Array (
		"time" => "Uhrzeit",
		"choose_month" => "Monat wählen",
		"all_month" => "alle Monate anzeigen",
		"page" => "Seite",
		"show" => "Anzeige",
		"of" => "von",
		"other_views" => "Alternative Ansichten",
		"month_view" => "Monatsansicht",
		"week_view" => "Wochenansicht",
		"list_view" => "Listenansicht",
		"year_view" => "Jahresansicht als PDF",
		"next_month" => "nächster Monat",
		"prev_month" => "vorheriger Monat",
		"next_week" => "nächste Woche",
		"prev_week" => "vorherige Woche",
		"filter_view" => "Anzeige Filtern",
		"all_cat" => "Alle Kategorien",
		"all_location" => "Alle Veranstaltungsorte",
		"all_organizer" => "Alle Veranstalter",
		"all_targetgroup" => "Alle Zielgruppen",
		"filter_error" => "Kein Filtern möglich, da mindestens zwei Kategorien, zwei Zielgruppen, zwei Veranstaltungsorte oder zwei Veranstalter angelegt sein müssen. Holen Sie dies entweder nach oder deaktivieren Sie diese Warnung.",
		"more" => "mehr",
		"here" => "hier",
		"cost" => "Kosten",
		"title" => "Titel",
		"location" => "Veranstaltungsort",
		"date" => "Datum",
		"back" => "Zurück",
		"further_information" => "Weitere Informationen",
		"category" => "Kategorie",
		"organizer" => "Veranstalter",
		"targetgroup" => "Zielgruppe",
		"dteinheit" => "Tag der dt. Einheit",
		"mai" => "Maifeiertag",
		"newyear" => "Neujahr",
		"threekings" => "Dreikönig",
		"christmas25" => "1. Weihnachtsf.",
		"advent1" => "1. Advent",
		"advent2" => "2. Advent",
		"advent3" => "3. Advent",
		"advent4" => "4. Advent",
		"easter" => "Ostern",
		"easterfr" => "Karfreitag",
		"pentacost" => "Pfingsten",
		"pentacostmo" => "Pfingstmontag",
		"mariaehf" => "Mariahimmelfahrt",
		"allerheilig" => "Allerheiligen",
		"christmas26" => "2. Weihnachtsf.",
		"christihf" => "Christ. Himmelf.",
		"fronleich" => "Fronleichnam",
		"pdf_generated" => "Der Kalender wurde erzeugt und der Download wird gestartet.",
		"dl_pdf" => "Sollte der Download nicht funktionieren klicken Sie bitte ",
		"description"=>"Beschreibung",
		"begin" => "Beginn",
		"clock" => "Uhr",
		"until" => "bis",
		"no_entries" => "Es wurden keine Einträge gefunden.",
		"do_filter" => "Anzeige Filtern",
		"searchword" => "Suchwort",
		"choose_cat" => "Kategorie wählen",
		"choose_loc" => "Veranstaltungsort wählen",
		"choose_org" => "Veranstalter wählen",
		"choose_tar" => "Zielgruppe wählen",
		"archive_make_selection" => "Bitte treffen Sie eine Auswahl um das Archiv zu durchsuchen.",
		
		// for registration module How could this be done more elegant?
		"tx_skcalregistration_register_date" => "Registrieren bis",
		"tx_skcalregistration_register_tolate" => "Registrierung nicht mehr möglich",
		"tx_skcalregistration_register_files" => "Dateien",
		"tx_skcalregistration_register_remarks" => "Infos zur Registrierung",	
	),
	"no" => Array (
	),
	"it" => Array (
	),
	"fr" => Array (
	),
	"es" => Array (
	),
	"nl" => Array (
	),
	"cz" => Array (
	),
	"pl" => Array (
	),
	"si" => Array (
	),
	"fi" => Array (
	),
	"tr" => Array (
	),
	"se" => Array (
	),
	"pt" => Array (
	),
	"ru" => Array (
	),
	"ro" => Array (
	),
	"ch" => Array (
	),
	"sk" => Array (
	),
	"lt" => Array (
	),
);
?>